### ISSUE TITLE
qt4 no longer builds 

### ISSUE THREAD

**Issue by bbjimmy** [qt-haiku/qt4#11]
Post the BControlLook API change, qt4 no longer builds.

**Comment by waddlesplash** [comment]
?

**Comment by waddlesplash** [comment]
Please post a link to a build log or the compile error that happens.

**Comment by bbjimmy** [comment]
http://coquillemartialarts.com/jim/libqt4-4.8.7.recipe.log

-- 
bbjimmy

http://www.coquillemartialarts.com
http://www.fatelk.com
http://yab.orgfree.com

**Comment by waddlesplash** [comment]
This is actually https://github.com/haikuports/haikuports/issues/1750.
