### ISSUE TITLE
lmms cmake qt build trouble 

### ISSUE THREAD

**Issue by SeanCollins** [qt-haiku/qt4#8]
linking this to the lmms page 

https://github.com/LMMS/lmms/issues/1820

**Comment by waddlesplash** [comment]
That's not a problem with Qt or LMMS, but rather with your build setup.

**Comment by SeanCollins** [comment]
Are there any clear concise instructions on how to setup the build environment ?

**Comment by waddlesplash** [comment]
No, not really. It's generally regarded as common packaging practices. The only thing different on Haiku is the GCC2/GCC4, thing, but for that, `setarch --help` is sufficient.

**Comment by SeanCollins** [comment]
Someone needs to write a clear concise guide for beginners to get involved. I frequently find the tangle of information hard to digest. In the meantime, it seems you have this handled and the help is greatly appreciated !

**Comment by waddlesplash** [comment]
Just read some books on C++, it's all in there. Mostly.

**Comment by SeanCollins** [comment]
Gonna make a go of it once we get settled in and unpacked. got any recomendations ?
